### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by toleson** [Ginurx/Blender-ACES-Config#1]
Hello there,

I'm sorry for posting this here, it might be a bit off. But I desperately need to make Blender work also without ACES and I found this really promising looking depository. I installed it following the instructions, but I can't figure out how to launch Blender with the sRGB or Filmic even after reading everything here. Please can someone reach out to me at yes@martinkohout.com and help me?

Thank you sincerely,
Martin

**Comment by Ginurx** [comment]
You can use method 2 in the readme. 
When you work with ACES workflow, start Blender from the batch file.
When  you work without ACES workflow, start Blender as usual from a desktop shortcut.
If you use color config in my repo, sRGB and Filmc is availabe in color management settings.
